"""
logger_v2.py - Paper Trading V2 Logger Module (SQLite + Ring Buffer)

Stores every signal-to-exit lifecycle for any asset (XAUUSD, EURUSD, etc.).
Written BEFORE sending the order (entry_planned / stop / target known),
then UPDATED after the order fills and exits.

Adds a user_action_log table for tracking GUI user actions.
Adds a system_logs table for the centralized System Logger (GUI_REWORK §5).

Schema columns for the signals table (spec section 5):

  event_id               TEXT PRIMARY KEY   - UUID v4, generated by log_signal()
  asset                  TEXT               - e.g. "XAUUSD" or "EURUSD"
  signal_time            TEXT (ISO-8601)    - when the signal engine fired
  confirmation_time      TEXT (ISO-8601)    - when the signal was confirmed
  features_json          TEXT               - JSON blob of signal features
  rule_score             REAL               - rule-based entry score
  model_probability      REAL               - model probability (0-1)
  entry_planned          REAL               - planned entry price
  stop_planned           REAL               - planned stop-loss price
  target_planned         REAL               - planned take-profit price
  order_sent_time        TEXT (ISO-8601)    - when the order was dispatched
  entry_actual           REAL               - actual fill price
  slippage_actual        REAL               - slippage = entry_actual - entry_planned (signed)
  exit_time              TEXT (ISO-8601)    - when the trade exited
  exit_price             REAL               - actual exit price
  exit_reason            TEXT               - e.g. "take_profit", "stop_loss", "manual_close"
  mfe_r                  REAL               - maximum favourable excursion in R multiples
  mae_r                  REAL               - maximum adverse excursion in R multiples
  net_result_r           REAL               - net result in R multiples
  automation_level       INTEGER            - 0=manual, 1=semi-auto, 2=full-auto
  kill_switch_status_at_signal  INTEGER     - 0=off, 1=on (blocking)

user_action_log table schema:

  id                     INTEGER PRIMARY KEY AUTOINCREMENT
  timestamp              TEXT (ISO-8601)    - when the action occurred
  action_type            TEXT               - e.g. "change_automation_level",
                                              "override_kill_switch",
                                              "send_order_click",
                                              "emergency_stop_toggle",
                                              "set_mcp_token",
                                              "reconnect_mcp"
  details_json           TEXT               - arbitrary JSON with action-specific fields

system_logs table schema (GUI_REWORK §5.7):

  id                     INTEGER PRIMARY KEY AUTOINCREMENT
  timestamp              TEXT (ISO-8601)    - when the log was created
  level                  TEXT NOT NULL      - DEBUG / INFO / WARNING / ERROR / CRITICAL
  source                 TEXT NOT NULL      - SignalEngine, RiskGuard, Execution, MCP, System, UserAction, etc.
  symbol                 TEXT               - instrument name or empty string
  message                TEXT NOT NULL      - human-readable log message
  extra_json             TEXT               - optional JSON blob for additional context

Dependencies: Python 3.10+ standard library only (sqlite3, uuid, datetime, collections, threading).
"""

import json
import sqlite3
import threading
import uuid
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

# ---------------------------------------------------------------------------
# Default database path (inside the same package directory)
# ---------------------------------------------------------------------------
DEFAULT_DB_PATH = Path(__file__).resolve().parent.parent / "db" / "paper_trading_v2.db"


def _iso_now() -> str:
    """Return current UTC timestamp as ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# Schema DDL — signals table + user_action_log table
# ---------------------------------------------------------------------------

_SIGNALS_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS signals (
    event_id                TEXT PRIMARY KEY,
    asset                   TEXT,
    signal_time             TEXT,
    confirmation_time       TEXT,
    features_json           TEXT,
    rule_score              REAL,
    model_probability       REAL,
    entry_planned           REAL,
    stop_planned            REAL,
    target_planned          REAL,
    order_sent_time         TEXT,
    entry_actual            REAL,
    slippage_actual         REAL,
    exit_time               TEXT,
    exit_price              REAL,
    exit_reason             TEXT,
    mfe_r                   REAL,
    mae_r                   REAL,
    net_result_r            REAL,
    automation_level        INTEGER,
    kill_switch_status_at_signal INTEGER
);
"""

_USER_ACTION_LOG_SQL = """
CREATE TABLE IF NOT EXISTS user_action_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp   TEXT NOT NULL,
    action_type TEXT NOT NULL,
    details_json TEXT
);
"""

_SYSTEM_LOGS_SQL = """
CREATE TABLE IF NOT EXISTS system_logs (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp   TEXT NOT NULL,
    level       TEXT NOT NULL,
    source      TEXT NOT NULL,
    symbol      TEXT,
    message     TEXT NOT NULL,
    extra_json  TEXT
);
"""

# Index on timestamp for time-range queries
_SYSTEM_LOGS_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS idx_system_logs_timestamp ON system_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_system_logs_level     ON system_logs(level);
CREATE INDEX IF NOT EXISTS idx_system_logs_symbol    ON system_logs(symbol);
CREATE INDEX IF NOT EXISTS idx_system_logs_source    ON system_logs(source);
"""

_SCHEMA_SQL = _SIGNALS_TABLE_SQL + _USER_ACTION_LOG_SQL + _SYSTEM_LOGS_SQL + _SYSTEM_LOGS_INDEX_SQL


# ---------------------------------------------------------------------------
# Connection management
# ---------------------------------------------------------------------------

def _get_connection(db_path: Optional[str] = None) -> sqlite3.Connection:
    """Return a sqlite3 connection to *db_path* (or DEFAULT_DB_PATH).

    Sets ``row_factory`` to ``sqlite3.Row`` so that cursor fetch methods
    return dictionary-like rows (usable via ``dict(row)``).

    Also ensures the required tables exist in case the DB was created
    by an older version of the module.
    """
    path = db_path if db_path is not None else str(DEFAULT_DB_PATH)
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL;")       # safe concurrent reads
    conn.execute("PRAGMA foreign_keys=ON;")
    # Ensure all required tables exist (idempotent)
    try:
        conn.executescript(_SCHEMA_SQL)
        conn.commit()
    except Exception:
        pass
    return conn


# ---------------------------------------------------------------------------
# In-memory ring buffer for real-time system log display (GUI_REWORK §5.5)
# Thread-safe: lock-protected writes and reads.
# ---------------------------------------------------------------------------

_RING_BUFFER_MAX = 10_000
_ring_buffer: deque = deque(maxlen=_RING_BUFFER_MAX)
_ring_lock = threading.Lock()


def _push_to_ring(entry: dict[str, Any]) -> None:
    """Append a log entry dict to the thread-safe ring buffer."""
    with _ring_lock:
        _ring_buffer.append(entry)


def get_ring_buffer() -> list[dict[str, Any]]:
    """Return a snapshot copy of the ring buffer (newest last).

    The returned list is a shallow copy — safe for the GUI to iterate
    without holding the lock.
    """
    with _ring_lock:
        return list(_ring_buffer)


def clear_ring_buffer() -> None:
    """Clear the in-memory ring buffer (e.g. on user 'Clear log')."""
    with _ring_lock:
        _ring_buffer.clear()


def clear_system_logs(db_path: Optional[str] = None) -> int:
    """Delete all rows from the system_logs table.

    Returns:
        Number of rows deleted.
    """
    conn = _get_connection(db_path)
    try:
        cursor = conn.execute("DELETE FROM system_logs")
        conn.commit()
        return cursor.rowcount
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def init_db(db_path: Optional[str] = None) -> str:
    """Create the SQLite database and both tables if they do not exist.

    Args:
        db_path: Full path to the ``.db`` file.  Defaults to
                 ``paper_trading_v2.db`` in the same directory as this module.

    Returns:
        The absolute path of the database file.
    """
    path = Path(db_path) if db_path else DEFAULT_DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = _get_connection(str(path))
    conn.executescript(_SCHEMA_SQL)
    conn.commit()
    conn.close()
    return str(path.resolve())


# ---------------------------------------------------------------------------
# Centralized System Logger (GUI_REWORK §5.7)
# ---------------------------------------------------------------------------

_LEVELS = frozenset(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"])


def log(
    level: str,
    source: str,
    symbol: Optional[str] = None,
    message: str = "",
    extra: Optional[dict[str, Any]] = None,
    *,
    db_path: Optional[str] = None,
) -> dict[str, Any]:
    """Centralized system log entry point.

    Writes to the ``system_logs`` SQLite table AND pushes to the
    in-memory ring buffer for real-time GUI display.

    Args:
        level: One of ``"DEBUG"``, ``"INFO"``, ``"WARNING"``,
               ``"ERROR"``, ``"CRITICAL"``.
        source: Module / component name, e.g. ``"SignalEngine"``,
                ``"RiskGuard"``, ``"Execution"``, ``"MCP"``, ``"System"``.
        symbol: Instrument name or ``None`` / empty string (optional).
        message: Human-readable log message.
        extra: Optional JSON-serializable dict with additional context
               (e.g. ``{"order_id": "123", "price": 2650.50}``).
        db_path: Override the database path.

    Returns:
        A dictionary representation of the inserted row.
    """
    # Validate level
    if level.upper() not in _LEVELS:
        level = "INFO"
    else:
        level = level.upper()

    now = _iso_now()
    extra_json = json.dumps(extra, default=str) if extra else None
    symbol_val = symbol if symbol else ""

    # 1. Write to SQLite
    conn = _get_connection(db_path)
    try:
        cursor = conn.execute(
            """
            INSERT INTO system_logs (timestamp, level, source, symbol, message, extra_json)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (now, level, source, symbol_val, message, extra_json),
        )
        conn.commit()
        row = conn.execute(
            "SELECT * FROM system_logs WHERE id = ?", (cursor.lastrowid,)
        ).fetchone()
        entry = _row_to_dict(row)
    finally:
        conn.close()

    # 2. Push to ring buffer
    _push_to_ring(entry)

    return entry


# ---------------------------------------------------------------------------
# System log query helpers
# ---------------------------------------------------------------------------


def query_system_logs(
    *,
    levels: Optional[list[str]] = None,
    sources: Optional[list[str]] = None,
    symbols: Optional[list[str]] = None,
    search_text: Optional[str] = None,
    time_from: Optional[str] = None,
    time_to: Optional[str] = None,
    limit: int = 10_000,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Query the system_logs table with optional filters.

    Args:
        levels: Filter by log level(s) — e.g. ``["INFO", "ERROR"]``.
                ``None`` means all levels.
        sources: Filter by source(s). ``None`` means all sources.
        symbols: Filter by symbol(s). ``None`` means all symbols.
        search_text: Full-text search on the message column.
        time_from: ISO-8601 start timestamp (inclusive).
        time_to: ISO-8601 end timestamp (inclusive).
        limit: Maximum rows to return (default 10_000).
        db_path: Override the database path.

    Returns:
        A list of row dictionaries (oldest first).
    """
    conditions: list[str] = []
    params: list[Any] = []

    if levels:
        placeholders = ",".join("?" for _ in levels)
        conditions.append(f"level IN ({placeholders})")
        params.extend(levels)
    if sources:
        placeholders = ",".join("?" for _ in sources)
        conditions.append(f"source IN ({placeholders})")
        params.extend(sources)
    if symbols:
        placeholders = ",".join("?" for _ in symbols)
        conditions.append(f"symbol IN ({placeholders})")
        params.extend(symbols)
    if search_text:
        conditions.append("message LIKE ?")
        params.append(f"%{search_text}%")
    if time_from:
        conditions.append("timestamp >= ?")
        params.append(time_from)
    if time_to:
        conditions.append("timestamp <= ?")
        params.append(time_to)

    where_clause = " AND ".join(conditions) if conditions else "1=1"

    sql = f"""
        SELECT * FROM system_logs
        WHERE {where_clause}
        ORDER BY timestamp ASC
        LIMIT ?
    """
    params.append(limit)

    conn = _get_connection(db_path)
    try:
        rows = conn.execute(sql, params).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


# ---------------------------------------------------------------------------


def log_signal(
    asset: str,
    signal_time: str,
    confirmation_time: str,
    features_json: str,
    rule_score: float,
    model_probability: float,
    entry_planned: float,
    stop_planned: float,
    target_planned: float,
    order_sent_time: str,
    automation_level: int,
    kill_switch_status_at_signal: int,
    *,
    event_id: Optional[str] = None,
    db_path: Optional[str] = None,
) -> dict[str, Any]:
    """Insert a new signal record and return it as a dictionary.

    Call this **BEFORE** sending the order to the execution layer so that
    the planned entry / stop / target are persisted before any fill data
    arrives.

    Args:
        asset: Instrument name, e.g. ``"XAUUSD"`` or ``"EURUSD"``.
        signal_time: ISO-8601 timestamp when the signal engine fired.
        confirmation_time: ISO-8601 timestamp when the signal was confirmed.
        features_json: Arbitrary JSON blob of signal features.
        rule_score: Scalar score from the rule-based component.
        model_probability: Model probability in [0, 1].
        entry_planned: Planned entry price.
        stop_planned: Planned stop-loss price.
        target_planned: Planned take-profit price.
        order_sent_time: ISO-8601 timestamp when the order was dispatched.
        automation_level: 0=manual, 1=semi-auto, 2=full-auto.
        kill_switch_status_at_signal: 0=off, 1=on.
        event_id: Optional caller-supplied UUID; a new UUID v4 is generated
                  if omitted.
        db_path: Override the database path.

    Returns:
        A dictionary representation of the inserted row.
    """
    eid = event_id if event_id is not None else str(uuid.uuid4())
    conn = _get_connection(db_path)
    try:
        conn.execute(
            """
            INSERT INTO signals (
                event_id, asset, signal_time, confirmation_time,
                features_json, rule_score, model_probability,
                entry_planned, stop_planned, target_planned,
                order_sent_time, automation_level,
                kill_switch_status_at_signal
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                eid,
                asset,
                signal_time,
                confirmation_time,
                features_json,
                rule_score,
                model_probability,
                entry_planned,
                stop_planned,
                target_planned,
                order_sent_time,
                automation_level,
                kill_switch_status_at_signal,
            ),
        )
        conn.commit()
        return _row_to_dict(
            conn.execute(
                "SELECT * FROM signals WHERE event_id = ?", (eid,)
            ).fetchone()
        )
    finally:
        conn.close()


def update_order_result(
    event_id: str,
    entry_actual: float,
    slippage_actual: float,
    exit_time: str,
    exit_price: float,
    exit_reason: str,
    mfe_r: float,
    mae_r: float,
    net_result_r: float,
    *,
    db_path: Optional[str] = None,
) -> Optional[dict[str, Any]]:
    """Update a previously logged signal with actual fill and exit data.

    Call this **AFTER** the trade closes to fill in the execution outcome.

    Args:
        event_id: The UUID of the signal to update.
        entry_actual: Actual fill price.
        slippage_actual: Signed difference (entry_actual - entry_planned).
        exit_time: ISO-8601 timestamp of exit.
        exit_price: Price at exit.
        exit_reason: Categorical reason.
        mfe_r: Maximum favourable excursion in R multiples.
        mae_r: Maximum adverse excursion in R multiples.
        net_result_r: Net result in R multiples.
        db_path: Override the database path.

    Returns:
        The updated row as a dictionary, or ``None`` if *event_id* is not
        found.
    """
    conn = _get_connection(db_path)
    try:
        cursor = conn.execute(
            """
            UPDATE signals
            SET entry_actual      = ?,
                slippage_actual   = ?,
                exit_time         = ?,
                exit_price        = ?,
                exit_reason       = ?,
                mfe_r             = ?,
                mae_r             = ?,
                net_result_r      = ?
            WHERE event_id = ?
            """,
            (
                entry_actual,
                slippage_actual,
                exit_time,
                exit_price,
                exit_reason,
                mfe_r,
                mae_r,
                net_result_r,
                event_id,
            ),
        )
        conn.commit()
        if cursor.rowcount == 0:
            return None
        return _row_to_dict(
            conn.execute(
                "SELECT * FROM signals WHERE event_id = ?", (event_id,)
            ).fetchone()
        )
    finally:
        conn.close()


def log_user_action(
    action_type: str,
    details_json: Optional[str] = None,
    *,
    db_path: Optional[str] = None,
) -> dict[str, Any]:
    """Log a user action (GUI interaction) to the user_action_log table.

    Args:
        action_type: A short string identifying the action, e.g.
                     ``"change_automation_level"``, ``"override_kill_switch"``,
                     ``"send_order_click"``, ``"emergency_stop_toggle"``,
                     ``"set_mcp_token"``, ``"reconnect_mcp"``.
        details_json: Optional JSON string with action-specific fields.
        db_path: Override the database path.

    Returns:
        A dictionary representation of the inserted row.
    """
    now = _iso_now()
    conn = _get_connection(db_path)
    try:
        c = conn.execute(
            "INSERT INTO user_action_log (timestamp, action_type, details_json) VALUES (?, ?, ?)",
            (now, action_type, details_json),
        )
        conn.commit()
        row = conn.execute(
            "SELECT * FROM user_action_log WHERE id = ?", (c.lastrowid,)
        ).fetchone()
        return _row_to_dict(row)
    finally:
        conn.close()


def get_recent_trades(
    asset: str,
    n: int = 20,
    *,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Return the *n* most recent trades for a given asset.

    Only rows that have an ``exit_time`` (i.e. completed trades) are
    returned, ordered by ``order_sent_time DESC``.

    This function is used by the Risk Guard module for block bootstrap
    kill-switch evaluation.

    Args:
        asset: Instrument name (e.g. ``"XAUUSD"``).
        n: Maximum number of rows (default 20).
        db_path: Override the database path.

    Returns:
        A list of row dictionaries (most recent first).
    """
    conn = _get_connection(db_path)
    try:
        rows = conn.execute(
            """
            SELECT * FROM signals
            WHERE asset = ? AND exit_time IS NOT NULL
            ORDER BY order_sent_time DESC
            LIMIT ?
            """,
            (asset, n),
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


def get_all_trades(
    *,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Return every signal row in the database.

    Rows are ordered by ``order_sent_time DESC`` so the most recent
    appears first.

    Args:
        db_path: Override the database path.

    Returns:
        A list of all row dictionaries.
    """
    conn = _get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT * FROM signals ORDER BY order_sent_time DESC"
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


def get_user_actions(
    n: int = 100,
    *,
    db_path: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Return the *n* most recent user action log entries.

    Args:
        n: Maximum number of rows (default 100).
        db_path: Override the database path.

    Returns:
        A list of row dictionaries (most recent first).
    """
    conn = _get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT * FROM user_action_log ORDER BY id DESC LIMIT ?",
            (n,),
        ).fetchall()
        return [_row_to_dict(r) for r in rows]
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    """Convert a ``sqlite3.Row`` to a plain ``dict``.

    If *row* is ``None``, returns an empty dict (should not happen with
    valid queries, but guards against callers that check truthiness).
    """
    if row is None:
        return {}
    return dict(row)