"""
generate_reports.py — DoD artifacts for Agent 4 (Wedge + Head & Shoulders).

Runs on the XAUUSD M15 dataset and writes (under the shared wedge pattern's
artifact dir):

* ``artifacts/reports/synthesizer_benchmark.md`` — §8.3 benchmark for the
  falling/rising wedge + head_shoulders + inverse_head_shoulders plugins;
  gates: recall ≥ 0.80 (falling + both H&S), robustness drop ≤ 0.15, FP ≤
  0.05.  rising_wedge is reported honestly (hard mirror — recursively the
  Agent 8 exclusion).
* ``artifacts/reports/gate_report_xauusd_m15.md`` — §6.3 research gates for
  all four directions (n / balance / ESS / PF CI / PR-AUC / WF), including
  the H&S sample-size caveat.
* ``artifacts/datasets/{falling_wedge,rising_wedge,head_shoulders,
  inverse_head_shoulders}_xauusd_m15.parquet`` — the labeled research
  datasets.

Usage:
    /tmp/ptv2_venv/bin/python research/patterns/rising_wedge/scripts/generate_reports.py
"""

from __future__ import annotations

from pathlib import Path

from research.patterns.falling_wedge.detector import FallingWedgeDetector
from research.patterns.head_shoulders.benchmark import (
    render_benchmark_report as render_hs_bench,
)
from research.patterns.head_shoulders.benchmark import (
    run_hs_benchmark,
)
from research.patterns.head_shoulders.dataset import (
    label_events,
    labeled_to_frame,
    load_xauusd_m15,
    render_gate_report,
    run_gates,
)
from research.patterns.head_shoulders.detector import HeadShouldersDetector
from research.patterns.inverse_head_shoulders.detector import (
    InverseHeadShouldersDetector,
)
from research.patterns.rising_wedge.benchmark import (
    render_benchmark_report as render_wedge_bench,
)
from research.patterns.rising_wedge.benchmark import (
    run_wedge_benchmark,
)
from research.patterns.rising_wedge.detector import RisingWedgeDetector

_ARTIFACTS = Path(__file__).resolve().parents[1] / "artifacts"
_REPORTS = _ARTIFACTS / "reports"
_DATASETS = _ARTIFACTS / "datasets"


def main() -> None:
    _REPORTS.mkdir(parents=True, exist_ok=True)
    _DATASETS.mkdir(parents=True, exist_ok=True)

    # --- §8.3 synthesizer benchmark --------------------------------------
    bench_lines = [
        "# Wedge + H&S Synthesizer Benchmark Report (§8.3) — Agent 4 DoD",
        "",
        "Generated by `scripts/generate_reports.py` on "
        "`research/core/pattern_synthesizer.py` (Agent 8 ground truth).",
        "Scale: 500 series/pattern + 2x-noise robustness + 500 pure-noise "
        "series (spec §8.3).",
        "",
    ]
    # wedges
    for pattern in ("falling_wedge", "rising_wedge"):
        res = run_wedge_benchmark(
            pattern, n_series=500, noise_sigma=0.05, n_noise_series=500, seed=42
        )
        bench_lines.append(render_wedge_bench(res))
        bench_lines.append("")
    # H&S
    for pattern in ("head_shoulders", "inverse_head_shoulders"):
        res = run_hs_benchmark(
            pattern, n_series=500, noise_sigma=0.05, n_noise_series=500, seed=42
        )
        bench_lines.append(render_hs_bench(res))
        bench_lines.append("")
    (_REPORTS / "synthesizer_benchmark.md").write_text("\n".join(bench_lines))

    # --- §6.3 research gates on XAUUSD M15 -------------------------------
    df = load_xauusd_m15()
    gate_lines = [
        "# Research Gate Report (§6.3) — Agent 4 DoD, XAUUSD M15",
        "",
        f"Dataset: {len(df)} M15 bars "
        f"({df.index[0]} → {df.index[-1]}).  Labeling: forward MFE/MAE, "
        f"fixed 72-bar horizon, label target 1.25R (see PATTERN_SPECS.md §8).",
        "",
        "Note: H&S is a rare reversal (true strict-structure events on M15 "
        "~150/208).  The §6.3 n >= 300 sample gate is calibrated for the "
        "common double patterns; H&S keeps the strict anti-noise detector "
        "and reports its gates at the true sample size (forcing n >= 300 "
        "would explode §8.3 FP to ~0.7 — a documented tradeoff).",
        "",
    ]
    for name, detector in (
        ("falling_wedge", FallingWedgeDetector()),
        ("rising_wedge", RisingWedgeDetector()),
        ("head_shoulders", HeadShouldersDetector()),
        ("inverse_head_shoulders", InverseHeadShouldersDetector()),
    ):
        events = detector.detect(df, detector.get_default_config())
        labeled = label_events(df, events)
        labeled_to_frame(labeled).to_parquet(
            _DATASETS / f"{name}_xauusd_m15.parquet", index=False
        )
        report = run_gates(df, events)
        gate_lines.append(f"## {name}")
        gate_lines.append(f"- detectors events: {len(events)} · labeled: {len(labeled)}")
        gate_lines.append(render_gate_report(report))
        gate_lines.append("")
    (_REPORTS / "gate_report_xauusd_m15.md").write_text("\n".join(gate_lines))

    print((_REPORTS / "synthesizer_benchmark.md").read_text())
    print((_REPORTS / "gate_report_xauusd_m15.md").read_text())


if __name__ == "__main__":  # pragma: no cover
    main()