"""Event → labeled dataset / trade records builder (guide sections 14-18, 26.3).

``build_event_labels`` is the canonical contract (``docs/INTERFACES.md``
section 6) for Pipeline 3: given the candle frame (with a causal ``atr``
column, added automatically when missing) and the sweep-event table, it adds,
one row per event:

* **identity** — ``event_id, event_time, direction`` (normalized to the
  canonical ``long``/``short``), ``level_id, level_price, atr`` (ATR at the
  sweep candle), ``entry_time, entry_price, stop_price, risk_price``;
* **targets** — ``target_{R}r`` for every reward multiple (``target_1r``,
  ``target_1_5r``, ``target_2r``);
* **excursions** — per horizon ``mfe_r_h{H}, mae_r_h{H}, close_return_r_h{H},
  max_close_return_r_h{H}, min_close_return_r_h{H}`` (guide 15/18; fixed
  window starting at the entry candle);
* **outcomes** — ``outcome_{R}r_h{H}`` for every (reward, horizon) combo,
  values ``tp | sl | time | ambiguous`` (canonical tokens,
  ``src/schema.py::OUTCOME_VALUES``; numeric labels 1/0/-1/NaN live in
  :mod:`src.labeling.triple_barrier` and map bijectively);
* **primary exit + costs** — for the primary combo
  (default ``(reward_r=2.0, horizon=16)`` = ``configs/baseline.yaml``
  ``model.target: outcome_2r_h16``): ``exit_time, exit_price, exit_reason,
  bars_held, ambiguous, bars_to_target, bars_to_stop, gross_result_r,
  cost_r, net_result_r``.

Entry mode (guide 14.1): baseline Phase 2 enters at the open of the candle
after the sweep (``entry.mode: next_open_after_sweep``).  When
``entry.mode: next_open_after_confirmation`` is configured the events must
carry the confirmation columns (``is_confirmed``, ``confirmation_time`` —
attached by Agent 3, Phase 5); confirmed events enter at the open after the
confirmation candle, unconfirmed ones are dropped as invalid.

Invalid events (guide 14.4 — ``risk <= 0``; plus ATR missing, entry beyond the
data, missing confirmation) are *dropped from the returned frame and reported*
in ``df.attrs["labeling_invalid"]`` / ``df.attrs["labeling_summary"]`` so the
ambiguity is never silent.  Nothing reads past the end of the candle frame.

Costs (guide 17) are applied on the raw geometry with exact formulas::

    gross_result_r = signed (exit_raw - entry_raw) / risk
    cost_r         = 2 * (half_spread_price + slippage_price) / risk
                     + commission_r          # commission in R units
    net_result_r   = gross_result_r - cost_r

``costs.half_spread_price`` / ``costs.slippage_price`` are PRICE units
(USD per oz of gold).  Data-engineering note (task t2): the raw MT5 SPREAD
column is in *points* (not price) and the parquet volume is tick volume; the
labeling pipeline reads neither — when a nonzero spread cost is configured the
caller must first convert points to price and put it under ``costs.*``.
Conversion reference (Data_Engineer, task t2): XAUUSD in this dataset quotes
with 2 decimals, so 1 price point = 0.01 USD/oz and
``half_spread_price = raw_spread_points * 0.01 / 2``; rows whose raw spread is
0 (5,215 rows, mostly 2022) need an explicit policy (e.g. floor by session
median) before real costs are enabled.  The legacy ``entry.spread_price`` /
``entry.slippage_price`` keys are rejected with a loud error if nonzero so
costs can never be silently understated.

``build_trade_records`` returns the same simulation in *long* form — one row
per (event, reward, horizon) — with the Agent-5 output schema (guide 5.6),
which the human-review stage (task t7) consumes for chart grouping.

Column names are generated by the helpers at the bottom of this module
(:func:`outcome_column`, :func:`target_column`, :func:`wide_schema_columns`)
so downstream consumers reference a single source of truth.

Causality of the decision bar (QA finding F1)
---------------------------------------------
Labeling treats ``event_time`` as *the* decision bar: entry is the open of the
candle right after it and every simulation is anchored there.  That bar must
therefore be causally decidable in real time — i.e. the first bar of a sweep
run.  Run-representative dedup rules such as t4's default
``deepest_penetration`` / ``strongest_reclaim`` pick a *later* bar of the same
run, which is only knowable in hindsight (intra-run look-ahead at the event
table level).  This module cannot repair that from the event table alone;
backtest/labeling runs must feed events generated with the causal rule
``group_rule="first"`` (or equivalently first-bar-of-run anchoring upstream,
Agent 3 / task t9).  Nothing in this module reads earlier or later candles of
the same run: every computation starts from the open of the candle after the
``event_time`` bar.
"""

from __future__ import annotations

import math
from collections.abc import Iterator, Mapping
from typing import Any

import numpy as np
import pandas as pd

from src.labeling.excursions import excursion_column_names, measure_excursions_arrays
from src.labeling.triple_barrier import (
    DIRECTION_LONG,
    DIRECTION_SHORT,
    EXIT_REASON_STOP,
    EXIT_REASON_TARGET,
    SAME_BAR_POLICIES,
    TIME_BARRIER_RESULTS,
    TOKEN_AMBIGUOUS,
    compute_trade_levels,
    label_event_arrays,
    outcome_to_token,
    validate_label_frame,
)

#: Directions accepted on the input event table (t4 emits bullish/bearish;
#: docs/SCHEMAS.md uses long/short).  Output is always canonical long/short.
_DIRECTION_ALIASES = {
    DIRECTION_LONG: DIRECTION_LONG,
    "bullish": DIRECTION_LONG,
    DIRECTION_SHORT: DIRECTION_SHORT,
    "bearish": DIRECTION_SHORT,
}

#: Hidden key that carries per-(reward,horizon) sims inside a wide row while
#: the event is processed; removed before any DataFrame is assembled.
_SIMS_KEY = "_sims"

_PRIMARY_COLUMNS = [
    "exit_time",
    "exit_price",
    "exit_reason",
    "bars_held",
    "ambiguous",
    "bars_to_target",
    "bars_to_stop",
    "gross_result_r",
    "cost_r",
    "net_result_r",
]

TRADE_RECORD_COLUMNS = [
    "event_id",
    "event_time",
    "direction",
    "reward_r",
    "horizon",
    "entry_time",
    "entry_price",
    "stop_price",
    "target_price",
    "risk_price",
    "outcome",
    "exit_time",
    "exit_price",
    "exit_reason",
    "mfe_r",
    "mae_r",
    "bars_held",
    "net_result_r",
    "ambiguous",
]


# ---------------------------------------------------------------------------
# Config resolution (sections of the merged YAML, or a flat dict)
# ---------------------------------------------------------------------------

def labeling_defaults() -> dict[str, Any]:
    """Default labeling configuration (mirrors ``configs/labeling.yaml``)."""
    return {
        "horizons": [4, 8, 16, 32],
        "reward_r_values": [1.0, 1.5, 2.0],
        "same_bar_policy": "ambiguous",
        "time_barrier_result": "mark_to_market",
        "primary_reward_r": 2.0,
        "primary_horizon": 16,
        "stop_buffer_atr": 0.10,
        "half_spread_price": 0.0,
        "slippage_price": 0.0,
        "commission_r": 0.0,
        "entry_mode": "next_open_after_sweep",
        "atr_period": 14,
    }


def resolve_labeling_config(config: Mapping[str, Any] | None) -> dict[str, Any]:
    """Normalize a (possibly nested) config mapping into flat labeling options.

    Accepts either the merged YAML shape — ``labeling`` / ``stop`` / ``costs``
    / ``entry`` / ``indicators`` sections — or a flat dict with the same keys
    as :func:`labeling_defaults`.  Missing keys keep defaults.  Invalid values
    raise ``ValueError`` naming the offending option.
    """
    cfg = labeling_defaults()

    def pick(*path: str) -> Any:
        node: Any = config or {}
        for key in path:
            if not isinstance(node, Mapping) or key not in node:
                return None
            node = node[key]
        return node

    horizons = pick("labeling", "horizons")
    rewards = pick("labeling", "reward_r_values")
    policy = pick("labeling", "same_bar_policy")
    time_result = pick("labeling", "time_barrier_result")
    primary_r = pick("labeling", "primary_reward_r")
    primary_h = pick("labeling", "primary_horizon")
    buffer_atr = pick("stop", "buffer_atr")
    half_spread = pick("costs", "half_spread_price")
    slippage = pick("costs", "slippage_price")
    commission = pick("costs", "commission_r")
    entry_mode = pick("entry", "mode")
    atr_period = pick("indicators", "atr_period")

    if horizons is not None:
        if (
            not isinstance(horizons, list)
            or not horizons
            or any(not isinstance(h, int) or isinstance(h, bool) or h < 1 for h in horizons)
        ):
            raise ValueError(
                f"resolve_labeling_config: labeling.horizons must be a "
                f"non-empty list of ints >= 1, got {horizons!r}"
            )
        cfg["horizons"] = list(dict.fromkeys(horizons))
    if rewards is not None:
        if (
            not isinstance(rewards, list)
            or not rewards
            or any(
                not isinstance(r, (int, float)) or isinstance(r, bool) or r <= 0
                for r in rewards
            )
        ):
            raise ValueError(
                f"resolve_labeling_config: labeling.reward_r_values must be a "
                f"non-empty list of positive numbers, got {rewards!r}"
            )
        cfg["reward_r_values"] = [float(r) for r in rewards]
    if policy is not None:
        if policy not in SAME_BAR_POLICIES:
            raise ValueError(
                f"resolve_labeling_config: labeling.same_bar_policy must be one "
                f"of {SAME_BAR_POLICIES}, got {policy!r}"
            )
        cfg["same_bar_policy"] = policy
    if time_result is not None:
        if time_result not in TIME_BARRIER_RESULTS:
            raise ValueError(
                f"resolve_labeling_config: labeling.time_barrier_result must be "
                f"one of {TIME_BARRIER_RESULTS}, got {time_result!r}"
            )
        cfg["time_barrier_result"] = time_result

    def _num(name: str, value: Any, minimum: float, strict: bool) -> None:
        if value is None:
            return
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            rel = ">" if strict else ">="
            raise ValueError(
                f"resolve_labeling_config: {name} must be a number {rel} "
                f"{minimum}, got {value!r}"
            )
        bound_ok = (value > minimum) if strict else (value >= minimum)
        if not bound_ok:
            rel = ">" if strict else ">="
            raise ValueError(
                f"resolve_labeling_config: {name} must be a number {rel} "
                f"{minimum}, got {value!r}"
            )

    _num("labeling.primary_reward_r", primary_r, 0.0, strict=True)
    if primary_r is not None:
        cfg["primary_reward_r"] = float(primary_r)
    if primary_h is not None:
        if not isinstance(primary_h, int) or isinstance(primary_h, bool) or primary_h < 1:
            raise ValueError(
                f"resolve_labeling_config: labeling.primary_horizon must be an "
                f"int >= 1, got {primary_h!r}"
            )
        cfg["primary_horizon"] = primary_h
    _num("stop.buffer_atr", buffer_atr, 0.0, strict=False)
    if buffer_atr is not None:
        cfg["stop_buffer_atr"] = float(buffer_atr)
    _num("costs.half_spread_price", half_spread, 0.0, strict=False)
    if half_spread is not None:
        cfg["half_spread_price"] = float(half_spread)
    _num("costs.slippage_price", slippage, 0.0, strict=False)
    if slippage is not None:
        cfg["slippage_price"] = float(slippage)
    _num("costs.commission_r", commission, 0.0, strict=False)
    if commission is not None:
        cfg["commission_r"] = float(commission)

    # Spread/slippage unit guard (Data_Engineer note, task t2): the raw MT5
    # SPREAD column is in POINTS, not price; `costs.*_price` keys are PRICE
    # units (USD/oz).  The separate `entry.spread_price` / `entry.slippage_price`
    # keys are NOT read by the labeling cost model — silently ignoring a
    # nonzero value there would understate costs, so fail loudly instead.
    for name, value in (
        ("entry.spread_price", pick("entry", "spread_price")),
        ("entry.slippage_price", pick("entry", "slippage_price")),
    ):
        if value is not None and (
            not isinstance(value, (int, float)) or isinstance(value, bool) or float(value) > 0
        ):
            raise ValueError(
                f"resolve_labeling_config: {name}={value!r} is not read by the "
                "labeling cost model; set costs.half_spread_price / "
                "costs.slippage_price instead, expressed in PRICE units "
                "(convert the raw MT5 SPREAD points -> price before "
                "configuring)"
            )

    if entry_mode is not None:
        if entry_mode not in ("next_open_after_sweep", "next_open_after_confirmation"):
            raise ValueError(
                f"resolve_labeling_config: entry.mode must be one of "
                f"{{next_open_after_sweep, next_open_after_confirmation}}, "
                f"got {entry_mode!r}"
            )
        cfg["entry_mode"] = entry_mode
    if atr_period is not None:
        if not isinstance(atr_period, int) or isinstance(atr_period, bool) or atr_period < 1:
            raise ValueError(
                f"resolve_labeling_config: indicators.atr_period must be an "
                f"int >= 1, got {atr_period!r}"
            )
        cfg["atr_period"] = atr_period

    # The primary (reward, horizon) combo must exist in the dataset.
    if (
        cfg["primary_reward_r"] not in cfg["reward_r_values"]
        or cfg["primary_horizon"] not in cfg["horizons"]
    ):
        raise ValueError(
            "resolve_labeling_config: primary combo "
            f"({cfg['primary_reward_r']}R, h{cfg['primary_horizon']}) must be "
            "present in labeling.reward_r_values and labeling.horizons"
        )
    return cfg


# ---------------------------------------------------------------------------
# Column-name helpers (single source of truth for downstream consumers)
# ---------------------------------------------------------------------------

def format_reward(reward_r: float) -> str:
    """Reward suffix used in column names: 1.0->'1', 1.5->'1_5', 2.0->'2'."""
    return f"{reward_r:g}".replace(".", "_")


def outcome_column(reward_r: float, horizon: int) -> str:
    """Column name of a (reward, horizon) outcome, e.g. ``outcome_2r_h16``."""
    return f"outcome_{format_reward(reward_r)}r_h{horizon}"


def target_column(reward_r: float) -> str:
    """Column name of a reward target price, e.g. ``target_1_5r``."""
    return f"target_{format_reward(reward_r)}r"


def wide_schema_columns(config: Mapping[str, Any] | None = None) -> list[str]:
    """Full ordered column list of :func:`build_event_labels` output."""
    cfg = resolve_labeling_config(config)
    cols: list[str] = [
        "event_id",
        "event_time",
        "direction",
        "level_id",
        "level_price",
        "atr",
        "entry_time",
        "entry_price",
        "stop_price",
        "risk_price",
    ]
    cols.extend(target_column(reward) for reward in cfg["reward_r_values"])
    for horizon in cfg["horizons"]:
        cols.extend(excursion_column_names(horizon))
    cols.extend(outcome_column(reward, horizon) for reward in cfg["reward_r_values"] for horizon in cfg["horizons"])
    cols.extend(_PRIMARY_COLUMNS)
    return cols


# ---------------------------------------------------------------------------
# Direction normalization
# ---------------------------------------------------------------------------

def normalize_direction(direction: Any) -> str:
    """Map detector direction values to canonical ``long``/``short``."""
    try:
        return _DIRECTION_ALIASES[str(direction)]
    except KeyError as exc:
        raise ValueError(
            f"normalize_direction: unknown event direction {direction!r}; "
            f"expected long|bullish|short|bearish"
        ) from exc


# ---------------------------------------------------------------------------
# Cost accounting (guide 17)
# ---------------------------------------------------------------------------

def cost_in_r(
    risk: float,
    half_spread_price: float,
    slippage_price: float,
    commission_r: float,
) -> float:
    """Round-trip cost expressed in R units.

    Spread + slippage are paid on entry *and* exit (guide 17.1/17.2:
    ``entry_effective = raw_entry ± (half_spread + slippage)`` and the mirror
    on exit), i.e. ``2 * (half_spread_price + slippage_price)`` in price units,
    converted by ``risk``; ``commission_r`` is already R-denominated.  All
    ``*_price`` arguments are PRICE units (USD/oz); the raw MT5 SPREAD column
    is points and must be converted before it is configured here.
    """
    return 2.0 * (half_spread_price + slippage_price) / risk + commission_r


def gross_result_in_r(direction: str, entry: float, exit_price: float, risk: float) -> float:
    """Raw (pre-cost) trade result in R units from the raw exit price."""
    if math.isnan(float(exit_price)):
        return float("nan")
    if direction == DIRECTION_LONG:
        return (float(exit_price) - float(entry)) / float(risk)
    return (float(entry) - float(exit_price)) / float(risk)


# ---------------------------------------------------------------------------
# Per-event simulation core
# ---------------------------------------------------------------------------

def _invalid_record(
    event_id: Any,
    event_time: Any,
    direction: str,
    reason: str,
) -> dict[str, Any]:
    return {
        "event_id": event_id,
        "event_time": event_time,
        "direction": direction,
        "reason": reason,
    }


def _simulate_event(
    highs: np.ndarray,
    lows: np.ndarray,
    opens: np.ndarray,
    closes: np.ndarray,
    atr: np.ndarray,
    times: pd.Index,
    event_id: Any,
    event_time: Any,
    raw_direction: str,
    sweep_pos: int,
    cfg: dict[str, Any],
    events: pd.DataFrame,
    row_idx: int,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    """Run the full (rewards x horizons) simulation for one event.

    Returns ``(wide_row, invalid_record)`` — exactly one is not ``None``.
    The wide row carries the hidden ``_SIMS_KEY`` with every (reward, horizon)
    sim dict (needed by the long trade-records builder); callers strip it.
    """
    direction = normalize_direction(raw_direction)
    n = len(highs)

    if cfg["entry_mode"] == "next_open_after_confirmation":
        is_confirmed = bool(events["is_confirmed"].iloc[row_idx])
        if not is_confirmed:
            return None, _invalid_record(event_id, event_time, direction, "no_confirmation")
        confirmation_time = events["confirmation_time"].iloc[row_idx]
        conf_pos = _position_of(events, row_idx, "confirmation_time", confirmation_time, times)
        entry_pos = conf_pos + 1
        if conf_pos <= sweep_pos:
            return None, _invalid_record(
                event_id, event_time, direction, "confirmation_not_after_sweep"
            )
    else:
        entry_pos = sweep_pos + 1

    if entry_pos >= n:
        return None, _invalid_record(event_id, event_time, direction, "no_next_bar")

    entry_price = float(opens[entry_pos])
    if not math.isfinite(entry_price):
        return None, _invalid_record(event_id, event_time, direction, "entry_nan")

    atr_value = float(atr[sweep_pos])
    if direction == DIRECTION_LONG:
        sweep_extreme = float(lows[sweep_pos])
    else:
        sweep_extreme = float(highs[sweep_pos])

    # Stop/risk do not depend on the reward multiple; use any configured one.
    levels = compute_trade_levels(
        direction,
        entry_price=entry_price,
        sweep_extreme=sweep_extreme,
        atr_value=atr_value,
        reward_r=cfg["reward_r_values"][0],
        stop_buffer_atr=cfg["stop_buffer_atr"],
    )
    risk = levels["risk"]
    if math.isnan(risk):
        return None, _invalid_record(event_id, event_time, direction, "atr_missing")
    if not math.isfinite(risk) or risk <= 0:
        return None, _invalid_record(event_id, event_time, direction, "risk_le_0")
    stop = levels["stop"]

    targets: dict[float, float] = {}
    for reward in cfg["reward_r_values"]:
        targets[reward] = (
            entry_price + reward * risk
            if direction == DIRECTION_LONG
            else entry_price - reward * risk
        )

    # ---- fixed-window excursions per horizon (guide 15) -------------------
    excursions: dict[int, dict[str, Any] | None] = {}
    for horizon in cfg["horizons"]:
        excursions[horizon] = measure_excursions_arrays(
            highs=highs,
            lows=lows,
            closes=closes,
            entry_pos=entry_pos,
            horizon=horizon,
            direction=direction,
            entry_price=entry_price,
            risk=risk,
        )

    # ---- triple-barrier sims per (reward, horizon) (guide 16) -------------
    sims: dict[tuple[float, int], dict[str, Any]] = {}
    for reward in cfg["reward_r_values"]:
        for horizon in cfg["horizons"]:
            sim = label_event_arrays(
                highs=highs,
                lows=lows,
                opens=opens,
                closes=closes,
                atr=atr,
                times=times,
                event_pos=sweep_pos,
                direction=direction,
                entry_pos=entry_pos,
                horizon=horizon,
                stop_buffer_atr=cfg["stop_buffer_atr"],
                reward_r=reward,
                same_bar_policy=cfg["same_bar_policy"],
                time_barrier_result=cfg["time_barrier_result"],
            )
            if sim is None:  # defensive: everything was pre-validated
                return None, _invalid_record(event_id, event_time, direction, "sim_failed")
            sims[(reward, horizon)] = sim

    # ---- assemble the wide row -------------------------------------------
    entry_time = times[entry_pos]
    wide: dict[str, Any] = {
        "event_id": event_id,
        "event_time": event_time,
        "direction": direction,
        "level_id": _optional_value(events, row_idx, "level_id"),
        "level_price": _optional_value(events, row_idx, "level_price"),
        "atr": float(atr_value),
        "entry_time": entry_time,
        "entry_price": float(entry_price),
        "stop_price": float(stop),
        "risk_price": float(risk),
    }
    for reward, target in targets.items():
        wide[target_column(reward)] = float(target)
    for horizon in cfg["horizons"]:
        exc = excursions[horizon]
        if exc is None:  # pragma: no cover - guarded by valid risk/entry above
            continue
        wide[f"mfe_r_h{horizon}"] = exc["mfe_r"]
        wide[f"mae_r_h{horizon}"] = exc["mae_r"]
        wide[f"close_return_r_h{horizon}"] = exc["close_return_r"]
        wide[f"max_close_return_r_h{horizon}"] = exc["max_close_return_r"]
        wide[f"min_close_return_r_h{horizon}"] = exc["min_close_return_r"]
    for reward in cfg["reward_r_values"]:
        for horizon in cfg["horizons"]:
            wide[outcome_column(reward, horizon)] = outcome_to_token(
                sims[(reward, horizon)]["outcome"]
            )

    primary = sims[(cfg["primary_reward_r"], cfg["primary_horizon"])]
    wide.update(_exit_and_cost_columns(primary, direction, cfg))
    wide[_SIMS_KEY] = sims
    return wide, None


def _position_of(
    events: pd.DataFrame,
    row_idx: int,
    column: str,
    value: Any,
    times: pd.Index,
) -> int:
    """Locate an event/confirmation timestamp inside the candle index."""
    positions = times.get_indexer(pd.DatetimeIndex([value]))
    pos = int(positions[0])
    if pos < 0:
        raise ValueError(
            f"build_event_labels: {column} value {value} of event "
            f"{events['event_id'].iloc[row_idx]!r} does not exist in the "
            "candle index; candles and events must come from the same frame"
        )
    return pos


def _optional_value(events: pd.DataFrame, row_idx: int, column: str) -> Any:
    if column in events.columns:
        return events[column].iloc[row_idx]
    return float("nan")


def _exit_and_cost_columns(
    sim: dict[str, Any],
    direction: str,
    cfg: dict[str, Any],
) -> dict[str, Any]:
    """Primary-combo exit metadata plus gross/cost/net result in R."""
    exit_reason = sim["exit_reason"]
    exit_price = float(sim["exit_price"])
    risk = float(sim["risk"])
    ambiguous = bool(sim["ambiguous"])
    bars_held = int(sim["bars_held"])

    cost = cost_in_r(
        risk=risk,
        half_spread_price=cfg["half_spread_price"],
        slippage_price=cfg["slippage_price"],
        commission_r=cfg["commission_r"],
    )
    gross = gross_result_in_r(direction, sim["entry"], exit_price, risk)

    bars_to_target: float
    bars_to_stop: float
    if exit_reason == EXIT_REASON_TARGET:
        bars_to_target, bars_to_stop = bars_held, float("nan")
    elif exit_reason == EXIT_REASON_STOP:
        bars_to_target, bars_to_stop = float("nan"), bars_held
    else:  # time barrier or ambiguous: no single barrier was hit
        bars_to_target, bars_to_stop = float("nan"), float("nan")

    return {
        "exit_time": sim["exit_time"],
        "exit_price": exit_price,
        "exit_reason": exit_reason,
        "bars_held": bars_held,
        "ambiguous": bool(ambiguous),
        "bars_to_target": bars_to_target,
        "bars_to_stop": bars_to_stop,
        "gross_result_r": float(gross),
        "cost_r": float(cost),
        "net_result_r": float(gross - cost) if not math.isnan(gross) else float("nan"),
    }


# ---------------------------------------------------------------------------
# Public pipeline entry points
# ---------------------------------------------------------------------------

def _prepare(
    candles: pd.DataFrame,
    events: pd.DataFrame,
    cfg: dict[str, Any],
) -> pd.DataFrame:
    """Validate inputs and ensure the candle frame carries a causal ``atr``."""
    if not isinstance(events, pd.DataFrame) or len(events) == 0:
        raise ValueError("events must be a non-empty DataFrame")
    required = [c for c in ("event_id", "event_time", "direction") if c not in events.columns]
    if required:
        raise ValueError(f"events missing required columns {required}")

    work = candles.copy()

    # The processed parquet artifact stores timestamps as a ``timestamp``
    # column on a RangeIndex; promote it to the canonical DatetimeIndex when
    # the frame has no time axis of its own (docs/SCHEMAS.md section 3).
    if not isinstance(work.index, pd.DatetimeIndex):
        if "timestamp" not in work.columns:
            raise ValueError(
                "candles must carry a datetime index (or a 'timestamp' column "
                "to promote); labeling needs a time axis to resolve events"
            )
        work = work.set_index("timestamp").sort_index()
        work = work[~work.index.duplicated(keep="first")]
    elif "timestamp" in work.columns:
        # Same time axis twice: keep the index as canonical, drop the column.
        if work["timestamp"].equals(pd.Series(work.index, index=work.index)):
            work = work.drop(columns=["timestamp"])

    if "atr" not in work.columns:
        from src.indicators.atr import add_atr  # local import: only when needed

        work = add_atr(work, period=cfg["atr_period"])
    validate_label_frame(work, func="build_event_labels")

    if cfg["entry_mode"] == "next_open_after_confirmation":
        missing = [
            c for c in ("is_confirmed", "confirmation_time") if c not in events.columns
        ]
        if missing:
            raise ValueError(
                "entry.mode is next_open_after_confirmation but events lack "
                f"confirmation columns {missing}; attach confirmations "
                "(Agent 3) or switch entry.mode to next_open_after_sweep"
            )
    return work


def _iter_simulated(
    work: pd.DataFrame,
    events: pd.DataFrame,
    cfg: dict[str, Any],
) -> Iterator[tuple[dict[str, Any] | None, dict[str, Any] | None]]:
    """Yield ``(wide_row_with_sims, invalid_record)`` for every event."""
    highs = work["high"].to_numpy(dtype=float)
    lows = work["low"].to_numpy(dtype=float)
    opens = work["open"].to_numpy(dtype=float)
    closes = work["close"].to_numpy(dtype=float)
    atr = work["atr"].to_numpy(dtype=float)
    times = work.index

    event_times = pd.DatetimeIndex(events["event_time"])
    positions = work.index.get_indexer(event_times)
    missing = int((positions < 0).sum())
    if missing:
        raise ValueError(
            f"{missing} event_time value(s) do not exist in the candle index; "
            "candles and events must come from the same frame"
        )

    for row_idx in range(len(events)):
        ev = events.iloc[row_idx]
        yield _simulate_event(
            highs=highs,
            lows=lows,
            opens=opens,
            closes=closes,
            atr=atr,
            times=times,
            event_id=ev["event_id"],
            event_time=ev["event_time"],
            raw_direction=ev["direction"],
            sweep_pos=int(positions[row_idx]),
            cfg=cfg,
            events=events,
            row_idx=row_idx,
        )


def _attach_invalid_attrs(out: pd.DataFrame, invalid_rows: list[dict[str, Any]]) -> None:
    """Attach audit metadata (config, dropped events, summary) to a result."""
    invalid_df = pd.DataFrame(invalid_rows)
    reasons: dict[str, int] = {}
    if len(invalid_df):
        reasons = invalid_df["reason"].value_counts().to_dict()
    out.attrs["labeling_invalid"] = invalid_df
    out.attrs["labeling_summary"] = {
        "n_invalid": len(invalid_df),
        "reasons": reasons,
    }


def build_event_labels(
    candles: pd.DataFrame,
    events: pd.DataFrame,
    config: Mapping[str, Any] | None = None,
) -> pd.DataFrame:
    """Pipeline 3 labeling entry point (contract ``docs/INTERFACES.md`` §6).

    Adds one row per *valid* event with the wide schema of
    :func:`wide_schema_columns` (identity, targets, per-horizon excursions,
    per-(reward,horizon) outcome tokens, primary exit + costs).  Invalid
    events (risk <= 0, missing ATR, no next bar, unconfirmed in
    confirmation-entry mode) are dropped and reported through the returned
    frame's ``attrs``:

    * ``attrs["labeling_config"]`` — the resolved config dict;
    * ``attrs["labeling_invalid"]`` — DataFrame of dropped events + reasons;
    * ``attrs["labeling_summary"]`` — ``{n_valid, n_invalid, reasons,
      n_ambiguous_primary, directions}``.
    """
    cfg = resolve_labeling_config(config)
    work = _prepare(candles, events, cfg)

    wide_rows: list[dict[str, Any]] = []
    invalid_rows: list[dict[str, Any]] = []
    for wide, invalid in _iter_simulated(work, events, cfg):
        if wide is not None:
            wide.pop(_SIMS_KEY, None)
            wide_rows.append(wide)
        else:
            assert invalid is not None
            invalid_rows.append(invalid)

    columns = wide_schema_columns(cfg)
    out = pd.DataFrame(wide_rows, columns=columns)
    out = out.sort_values("event_time", kind="stable").reset_index(drop=True)

    primary_col = outcome_column(cfg["primary_reward_r"], cfg["primary_horizon"])
    out.attrs["labeling_config"] = cfg
    _attach_invalid_attrs(out, invalid_rows)
    summary = dict(out.attrs["labeling_summary"])
    summary.update(
        {
            "n_valid": len(out),
            "n_ambiguous_primary": int((out[primary_col] == TOKEN_AMBIGUOUS).sum()),
            "directions": out["direction"].value_counts().to_dict(),
        }
    )
    out.attrs["labeling_summary"] = summary
    return out


def build_trade_records(
    candles: pd.DataFrame,
    events: pd.DataFrame,
    config: Mapping[str, Any] | None = None,
) -> pd.DataFrame:
    """Long-format trade records — one row per (event, reward, horizon).

    Columns follow the Agent-5 output schema (guide 5.6) plus ``reward_r`` /
    ``horizon`` / ``event_time`` keys; ``outcome`` holds the canonical token
    (``tp/sl/time/ambiguous``), ``mfe_r``/``mae_r`` are the excursions up to
    the exit (guide 16.2 semantics), ``net_result_r`` is cost-adjusted
    (guide 17).  Invalid events are dropped and reported through ``attrs``
    exactly as in :func:`build_event_labels`.
    """
    cfg = resolve_labeling_config(config)
    work = _prepare(candles, events, cfg)

    records: list[dict[str, Any]] = []
    invalid_rows: list[dict[str, Any]] = []
    for wide, invalid in _iter_simulated(work, events, cfg):
        if wide is None:
            assert invalid is not None
            invalid_rows.append(invalid)
            continue
        sims = wide.pop(_SIMS_KEY)
        direction = wide["direction"]
        risk = float(wide["risk_price"])
        cost = cost_in_r(
            risk=risk,
            half_spread_price=cfg["half_spread_price"],
            slippage_price=cfg["slippage_price"],
            commission_r=cfg["commission_r"],
        )
        for reward in cfg["reward_r_values"]:
            for horizon in cfg["horizons"]:
                sim = sims[(reward, horizon)]
                exit_price = float(sim["exit_price"])
                gross = gross_result_in_r(direction, wide["entry_price"], exit_price, risk)
                records.append(
                    {
                        "event_id": wide["event_id"],
                        "event_time": wide["event_time"],
                        "direction": direction,
                        "reward_r": float(reward),
                        "horizon": int(horizon),
                        "entry_time": wide["entry_time"],
                        "entry_price": wide["entry_price"],
                        "stop_price": wide["stop_price"],
                        "target_price": wide[target_column(reward)],
                        "risk_price": risk,
                        "outcome": outcome_to_token(float(sim["outcome"])),
                        "exit_time": sim["exit_time"],
                        "exit_price": exit_price,
                        "exit_reason": sim["exit_reason"],
                        "mfe_r": float(sim["mfe_r"]),
                        "mae_r": float(sim["mae_r"]),
                        "bars_held": int(sim["bars_held"]),
                        "net_result_r": (
                            float(gross - cost) if not math.isnan(gross) else float("nan")
                        ),
                        "ambiguous": bool(sim["ambiguous"]),
                    }
                )

    out = pd.DataFrame(records, columns=TRADE_RECORD_COLUMNS)
    out = out.sort_values(["event_time", "reward_r", "horizon"], kind="stable").reset_index(
        drop=True
    )
    out.attrs["labeling_config"] = cfg
    _attach_invalid_attrs(out, invalid_rows)
    summary = dict(out.attrs["labeling_summary"])
    summary.update(
        {
            "n_valid_events": int(out["event_id"].nunique()),
            "n_records": len(out),
        }
    )
    out.attrs["labeling_summary"] = summary
    return out
