"""
generate_reports.py — DoD artifacts for Agent 3 (Double Bottom/Top).

Runs on the XAUUSD M15 dataset and writes:

* ``artifacts/reports/synthesizer_benchmark.md``  — §8.3 benchmark for both
  double plugins (recall / robustness / FP);
* ``artifacts/reports/gate_report_xauusd_m15.md`` — §6.3 research gates for
  both directions (n / balance / ESS / PF CI / PR-AUC / WF folds);
* ``artifacts/datasets/double_bottom_xauusd_m15.parquet`` /
  ``double_top_xauusd_m15.parquet`` — the labeled research datasets.

Usage:
    /tmp/ptv2_venv/bin/python research/patterns/double_bottom/scripts/generate_reports.py
"""

from __future__ import annotations

from pathlib import Path

from research.patterns.double_bottom.benchmark import (
    render_benchmark_report,
    run_double_benchmark,
)
from research.patterns.double_bottom.dataset import (
    label_events,
    labeled_to_frame,
    load_xauusd_m15,
    render_gate_report,
    run_gates,
)
from research.patterns.double_bottom.detector import DoubleBottomDetector
from research.patterns.double_top.detector import DoubleTopDetector

_ARTIFACTS = Path(__file__).resolve().parents[1] / "artifacts"
_REPORTS = _ARTIFACTS / "reports"
_DATASETS = _ARTIFACTS / "datasets"


def main() -> None:
    _REPORTS.mkdir(parents=True, exist_ok=True)
    _DATASETS.mkdir(parents=True, exist_ok=True)

    # --- §8.3 synthesizer benchmark --------------------------------------
    bench_lines = [
        "# Double-Pattern Synthesizer Benchmark Report (§8.3) — Agent 3 DoD",
        "",
        "Generated by `scripts/generate_reports.py` on "
        "`research/core/pattern_synthesizer.py` (Agent 8 ground truth).",
        "Scale: 500 series/pattern + 2x-noise robustness + 500 pure-noise "
        "series (spec §8.3).",
        "",
    ]
    for pattern in ("double_bottom", "double_top"):
        res = run_double_benchmark(
            pattern, n_series=500, noise_sigma=0.05, n_noise_series=500, seed=42
        )
        bench_lines.append(render_benchmark_report(res))
        bench_lines.append("")
    (_REPORTS / "synthesizer_benchmark.md").write_text("\n".join(bench_lines))

    # --- §6.3 research gates on XAUUSD M15 -------------------------------
    df = load_xauusd_m15()
    gate_lines = [
        "# Research Gate Report (§6.3) — Agent 3 DoD, XAUUSD M15",
        "",
        f"Dataset: {len(df)} M15 bars "
        f"({df.index[0]} → {df.index[-1]}).  Labeling: forward MFE/MAE, "
        f"fixed 72-bar horizon, label target 1.25R (see PATTERN_SPECS.md §8).",
        "",
    ]
    for name, detector in (
        ("double_bottom", DoubleBottomDetector()),
        ("double_top", DoubleTopDetector()),
    ):
        events = detector.detect(df, detector.get_default_config())
        labeled = label_events(df, events)
        labeled_to_frame(labeled).to_parquet(
            _DATASETS / f"{name}_xauusd_m15.parquet", index=False
        )
        report = run_gates(df, events)
        gate_lines.append(f"## {name}")
        gate_lines.append(
            f"- detectors events: {len(events)} · labeled events: {len(labeled)}"
        )
        gate_lines.append(render_gate_report(report))
        gate_lines.append("")
    (_REPORTS / "gate_report_xauusd_m15.md").write_text("\n".join(gate_lines))

    print((_REPORTS / "synthesizer_benchmark.md").read_text())
    print((_REPORTS / "gate_report_xauusd_m15.md").read_text())


if __name__ == "__main__":  # pragma: no cover
    main()